Reorganize code

diff --git a/argon1-ubuntu b/argon1-ubuntu
--- a/argon1-ubuntu
+++ b/argon1-ubuntu
@@ -1,40 +1,5 @@
 #!/usr/bin/env bash
 
-# Check if the user running the script is root
-if [[ "$(id -u)" -ne 0 ]]; then
-  echo "[!] ERROR: You need to be root."
-  exit 1
-fi
-
-if [[ "${HOSTTYPE}" != "arm" ]] && [[ "${HOSTTYPE}" != "aarch64" ]]; then
-  echo "[!] This script is only intended to run on ARM devices."
-  exit 1
-fi
-
-# Check if we're running on a Raspberry Pi
-if [[ -e /proc/device-tree/model ]]; then
-  read -r -d $'\0' PI_MODEL </proc/device-tree/model
-fi
-if [[ "${PI_MODEL:-}" =~ ^Raspberry.Pi.*$ ]]; then
-  echo "[+] Configuring your ${PI_MODEL}"
-else
-  echo "[!] This is not a Raspberry Pi. Quitting!"
-  exit 1
-fi
-
-# Check if we're running Ubuntu
-IS_UBUNTU=$(lsb_release -is)
-if [[ "${IS_UBUNTU}" != "Ubuntu" ]]; then
-  echo "[!] This script is only intended to run on Ubuntu."
-  exit 1
-fi
-
-daemonname="argononed"
-powerbuttonscript="/usr/local/bin/${daemonname}"
-shutdownscript="/lib/systemd/system-shutdown/${daemonname}-poweroff"
-daemonconfigfile="/etc/${daemonname}.conf"
-daemonfanservice="/lib/systemd/system/${daemonname}.service"
-
 # Display help usage
 function usage () {
   echo
@@ -290,6 +255,41 @@ function uninstall_argonone() {
     echo "Removed Argon One Services."
     echo "Cleanup will complete after restarting the device."
 }
+
+# Check if the user running the script is root
+if [[ "$(id -u)" -ne 0 ]]; then
+  echo "[!] ERROR: You need to be root."
+  exit 1
+fi
+
+if [[ "${HOSTTYPE}" != "arm" ]] && [[ "${HOSTTYPE}" != "aarch64" ]]; then
+  echo "[!] This script is only intended to run on ARM devices."
+  exit 1
+fi
+
+# Check if we're running on a Raspberry Pi
+if [[ -e /proc/device-tree/model ]]; then
+  read -r -d $'\0' PI_MODEL </proc/device-tree/model
+fi
+if [[ "${PI_MODEL:-}" =~ ^Raspberry.Pi.*$ ]]; then
+  echo "[+] Configuring your ${PI_MODEL}"
+else
+  echo "[!] This is not a Raspberry Pi. Quitting!"
+  exit 1
+fi
+
+# Check if we're running Ubuntu
+IS_UBUNTU=$(lsb_release -is)
+if [[ "${IS_UBUNTU}" != "Ubuntu" ]]; then
+  echo "[!] This script is only intended to run on Ubuntu."
+  exit 1
+fi
+
+daemonname="argononed"
+powerbuttonscript="/usr/local/bin/${daemonname}"
+shutdownscript="/lib/systemd/system-shutdown/${daemonname}-poweroff"
+daemonconfigfile="/etc/${daemonname}.conf"
+daemonfanservice="/lib/systemd/system/${daemonname}.service"
 
 # Take command line arguments
 if [[ $# -lt 1 ]]; then
