Refactor argument parsing

diff --git a/argon1-ubuntu b/argon1-ubuntu
--- a/argon1-ubuntu
+++ b/argon1-ubuntu
@@ -252,6 +252,16 @@ function uninstall_argonone() {
     echo "Cleanup will complete after restarting the device."
 }
 
+# Check number of command line arguments
+if [[ $# -lt 1 ]]; then
+    usage >&2
+    exit 1
+elif [[ $# -gt 1 ]]; then
+    echo "[!] ERROR: Too many arguments."
+    usage >&2
+    exit 1
+fi
+
 # Check if the user running the script is root
 if [[ "$(id -u)" -ne 0 ]]; then
     echo "[!] ERROR: You need to be root."
@@ -285,37 +295,27 @@ shutdownscript="/lib/systemd/system-shutdown/${daemonname}-poweroff"
 daemonconfigfile="/etc/${daemonname}.conf"
 daemonfanservice="/lib/systemd/system/${daemonname}.service"
 
-# Take command line arguments
-if [[ $# -lt 1 ]]; then
-    usage
-    exit 0
-else
-    while [[ $# -gt 0 ]]; do
-        case "${1}" in
-            -c | --config)
-                shift
-                config_argonone
-                exit 0
-                ;;
-            -i | --install)
-                shift
-                install_argonone
-                exit 0
-                ;;
-            -u | --uninstall)
-                shift
-                uninstall_argonone
-                exit 0
-                ;;
-            -h | --help)
-                usage
-                exit 0
-                ;;
-            *)
-                echo "[!] ERROR: \"${1}\" is not a supported parameter."
-                usage
-                exit 1
-                ;;
-        esac
-    done
-fi
+# Parse command line arguments
+case "${1}" in
+    -c | --config)
+        config_argonone
+        exit 0
+        ;;
+    -i | --install)
+        install_argonone
+        exit 0
+        ;;
+    -u | --uninstall)
+        uninstall_argonone
+        exit 0
+        ;;
+    -h | --help)
+        usage
+        exit 0
+        ;;
+    *)
+        echo "[!] ERROR: \"${1}\" is not a supported parameter." >&2
+        usage >@2
+        exit 1
+        ;;
+esac
